---
ms.date: 09/13/2016
ms.topic: reference
title: Fouten waarbij de functie of bewerking wordt beëindigd
description: Fouten waarbij de functie of bewerking wordt beëindigd
ms.openlocfilehash: b7c9b949a654f10a0421ea69dfe955c8dfb5627e
ms.sourcegitcommit: 488a940c7c828820b36a6ba56c119f64614afc29
ms.translationtype: MT
ms.contentlocale: nl-NL
ms.lasthandoff: 10/27/2020
ms.locfileid: "92652549"
---
# <a name="terminating-errors"></a><span data-ttu-id="ef88a-103">Fouten waarbij de functie of bewerking wordt beëindigd</span><span class="sxs-lookup"><span data-stu-id="ef88a-103">Terminating Errors</span></span>

<span data-ttu-id="ef88a-104">In dit onderwerp wordt de methode beschreven die wordt gebruikt voor het rapporteren van afsluit fouten.</span><span class="sxs-lookup"><span data-stu-id="ef88a-104">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="ef88a-105">Ook wordt beschreven hoe u de methode aanroept vanuit de cmdlet en worden de uitzonde ringen beschreven die kunnen worden geretourneerd door de Windows Power shell-runtime wanneer de methode wordt aangeroepen.</span><span class="sxs-lookup"><span data-stu-id="ef88a-105">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="ef88a-106">Als er een afsluit fout optreedt, moet de cmdlet de fout rapporteren door de methode [System. Management. Automation. cmdlet. Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) aan te roepen.</span><span class="sxs-lookup"><span data-stu-id="ef88a-106">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="ef88a-107">Met deze methode kan de cmdlet een fout record verzenden waarin de voor waarde wordt beschreven die de afsluit fout heeft veroorzaakt.</span><span class="sxs-lookup"><span data-stu-id="ef88a-107">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="ef88a-108">Zie [Windows Power Shell-fout records](./windows-powershell-error-records.md)voor meer informatie over fout records.</span><span class="sxs-lookup"><span data-stu-id="ef88a-108">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="ef88a-109">Bij het aanroepen van de methode [System. Management. Automation. cmdlet. Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) wordt de uitvoering van de pijp lijn permanent gestopt en wordt een [System. Management. Automation. Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) -uitzonde ring gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="ef88a-109">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="ef88a-110">Eventuele daaropvolgende pogingen om [System. Management. Automation. cmdlet. WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System. Management. Automation](/dotnet/api/System.Management.Automation.Cmdlet.WriteError). cmdlet. WriteError of verschillende andere api's aan te roepen, veroorzaken deze aanroepen om een uitzonde ring [System. Management. Automation. Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) uit te voeren.</span><span class="sxs-lookup"><span data-stu-id="ef88a-110">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="ef88a-111">De uitzonde ring [System. Management. Automation. Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) kan ook optreden als een andere cmdlet in de pijp lijn een afsluit fout rapporteert, als de gebruiker heeft gevraagd de pijp lijn te stoppen of als de pijp lijn om een of andere reden is gestopt.</span><span class="sxs-lookup"><span data-stu-id="ef88a-111">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="ef88a-112">De cmdlet hoeft de uitzonde ring [System. Management. Automation. Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) niet te ondervangen, tenzij open bronnen of de interne status ervan moeten worden opgeruimd.</span><span class="sxs-lookup"><span data-stu-id="ef88a-112">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="ef88a-113">Met cmdlets kunt u elk wille keurig aantal uitvoer objecten of niet-afsluit fouten schrijven voordat u een afsluit fout rapporteert.</span><span class="sxs-lookup"><span data-stu-id="ef88a-113">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="ef88a-114">De afsluit fout stopt echter permanent de pijp lijn en er kunnen geen verdere uitvoer, afsluit fouten of niet-afsluit fouten worden gerapporteerd.</span><span class="sxs-lookup"><span data-stu-id="ef88a-114">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="ef88a-115">Met cmdlets kan [System. Management. Automation. cmdlet. Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) alleen worden aangeroepen vanuit de thread met de naam [System. Management. Automation. cmdlet. BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System. Management](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord). Automation. cmdlet. ProcessRecord of [System. Management.](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) Automation. cmdlet. EndProcessing-invoer methode.</span><span class="sxs-lookup"><span data-stu-id="ef88a-115">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="ef88a-116">Probeer [System. Management. Automation. cmdlet. Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) of [System. Management. Automation. cmdlet. WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) niet aan te roepen vanuit een andere thread.</span><span class="sxs-lookup"><span data-stu-id="ef88a-116">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="ef88a-117">In plaats daarvan moeten fouten worden teruggestuurd naar de hoofd thread.</span><span class="sxs-lookup"><span data-stu-id="ef88a-117">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="ef88a-118">Het is mogelijk dat een cmdlet een uitzonde ring genereert in de implementatie van [System. Management. Automation. cmdlet. BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System. Management.](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)Automation. cmdlet. ProcessRecord of [System. Management.](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) Automation. cmdlet. EndProcessing.</span><span class="sxs-lookup"><span data-stu-id="ef88a-118">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="ef88a-119">Een uitzonde ring die is gegenereerd op basis van deze methoden (met uitzonde ring van enkele ernstige fout situaties die de Windows Power shell-host stoppen) wordt geïnterpreteerd als een afsluit fout waardoor de pijp lijn wordt gestopt, maar niet Windows Power shell als geheel.</span><span class="sxs-lookup"><span data-stu-id="ef88a-119">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="ef88a-120">(Dit geldt alleen voor de hoofd-cmdlet-thread.</span><span class="sxs-lookup"><span data-stu-id="ef88a-120">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="ef88a-121">Niet-onderschepte uitzonde ringen in threads die worden geïnitieerd door de cmdlet, in het algemeen, stopt u de Windows Power shell-host.) U wordt aangeraden [System. Management. Automation. cmdlet. Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) te gebruiken in plaats van een uitzonde ring uit te voeren, omdat de fout record aanvullende informatie bevat over de fout voorwaarde, die nuttig is voor de eind gebruiker.</span><span class="sxs-lookup"><span data-stu-id="ef88a-121">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="ef88a-122">Cmdlets moeten voldoen aan de richt lijnen voor beheerde code voor het uitvoeren en afhandelen van alle uitzonde ringen ( `catch (Exception e)` ).</span><span class="sxs-lookup"><span data-stu-id="ef88a-122">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="ef88a-123">Converteer alleen uitzonde ringen van bekende en verwachte typen naar fout records.</span><span class="sxs-lookup"><span data-stu-id="ef88a-123">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="ef88a-124">Zie ook</span><span class="sxs-lookup"><span data-stu-id="ef88a-124">See Also</span></span>

[<span data-ttu-id="ef88a-125">System. Management. Automation. cmdlet. BeginProcessing</span><span class="sxs-lookup"><span data-stu-id="ef88a-125">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="ef88a-126">System. Management. Automation. cmdlet. EndProcessing</span><span class="sxs-lookup"><span data-stu-id="ef88a-126">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="ef88a-127">System. Management. Automation. cmdlet. ProcessRecord</span><span class="sxs-lookup"><span data-stu-id="ef88a-127">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="ef88a-128">System. Management. Automation. Pipelinestoppedexception</span><span class="sxs-lookup"><span data-stu-id="ef88a-128">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="ef88a-129">System. Management. Automation. cmdlet. Throwterminatingerror \*</span><span class="sxs-lookup"><span data-stu-id="ef88a-129">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="ef88a-130">System. Management. Automation. cmdlet. WriteError</span><span class="sxs-lookup"><span data-stu-id="ef88a-130">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="ef88a-131">Windows PowerShell-foutrecords</span><span class="sxs-lookup"><span data-stu-id="ef88a-131">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="ef88a-132">Een Windows PowerShell-cmdlet schrijven</span><span class="sxs-lookup"><span data-stu-id="ef88a-132">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
