---
title: Fouten en uitzonde ringen in het uitgebreide-type systeem
ms.date: 07/09/2020
ms.openlocfilehash: f60c53e33c031168eda53726e0d296bf91139fda
ms.sourcegitcommit: 0907b8c6322d2c7c61b17f8168d53452c8964b41
ms.translationtype: MT
ms.contentlocale: nl-NL
ms.lasthandoff: 08/05/2020
ms.locfileid: "87786285"
---
# <a name="errors-and-exceptions-in-the-extended-type-system"></a><span data-ttu-id="663d0-102">Fouten en uitzonde ringen in het uitgebreide-type systeem</span><span class="sxs-lookup"><span data-stu-id="663d0-102">Errors and exceptions in the Extended Type System</span></span>

<span data-ttu-id="663d0-103">Er kunnen fouten optreden in ETS tijdens de initialisatie van type gegevens en bij het openen van een lid van een **PSObject** -object of het gebruik van een van de hulpprogramma klassen zoals **LanguagePrimitives**.</span><span class="sxs-lookup"><span data-stu-id="663d0-103">Errors can occur in ETS during the initialization of type data and when accessing a member of an **PSObject** object or using one of the utility classes such as **LanguagePrimitives**.</span></span>

## <a name="runtime-errors"></a><span data-ttu-id="663d0-104">Runtime-fouten</span><span class="sxs-lookup"><span data-stu-id="663d0-104">Runtime errors</span></span>

<span data-ttu-id="663d0-105">Met één uitzonde ring, wanneer cast, worden alle uitzonde ringen die tijdens runtime worden gegenereerd, een **ExtendedTypeSystemException** -uitzonde ring of een uitzonde ring die is afgeleid van de **ExtendedTypeSystemException** -klasse.</span><span class="sxs-lookup"><span data-stu-id="663d0-105">With one exception, when casting, all exceptions thrown from ETS during runtime are either an **ExtendedTypeSystemException** exception or an exception derived from the **ExtendedTypeSystemException** class.</span></span> <span data-ttu-id="663d0-106">Hierdoor kunnen script ontwikkelaars deze uitzonde ringen overvullen met behulp van de- `Trap` instructie in hun script.</span><span class="sxs-lookup"><span data-stu-id="663d0-106">This allows script developers to trap these exceptions using the `Trap` statement in their script.</span></span>

## <a name="errors-getting-member-values"></a><span data-ttu-id="663d0-107">Fouten bij het ophalen van leden waarden</span><span class="sxs-lookup"><span data-stu-id="663d0-107">Errors getting member values</span></span>

<span data-ttu-id="663d0-108">Bij alle fouten die optreden wanneer de waarde van een ETS-lid (eigenschap, methode of geparametriseerde eigenschap) wordt opgehaald, wordt een **GetValueException** -of **GetValueInvocationException** -uitzonde ring gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-108">All errors that occur when getting the value of an ETS member (property, method, or parameterized property) cause a **GetValueException** or **GetValueInvocationException** exception to be thrown.</span></span>
<span data-ttu-id="663d0-109">Wanneer ETS detecteert dat er een fout is opgetreden, wordt een **GetValueException** -uitzonde ring gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-109">When ETS recognizes that an error occurred a **GetValueException** exception is thrown.</span></span> <span data-ttu-id="663d0-110">Wanneer de onderliggende getter van een lid waarnaar wordt verwezen, detecteert dat er een fout is opgetreden, wordt een **GetValueInvocationException** -uitzonde ring gegenereerd die de interne uitzonde ring kan bevatten die de aanroep fout heeft veroorzaakt.</span><span class="sxs-lookup"><span data-stu-id="663d0-110">When the underlying getter of a referenced member recognizes that an error occurred, a **GetValueInvocationException** exception is thrown that may or may not include the inner exception that caused the get invocation error.</span></span>

## <a name="errors-setting-member-values"></a><span data-ttu-id="663d0-111">Fouten bij het instellen van leden waarden</span><span class="sxs-lookup"><span data-stu-id="663d0-111">Errors setting member values</span></span>

<span data-ttu-id="663d0-112">Alle fouten die optreden bij het instellen van de waarde van een ETS-eigenschap veroorzaken een **SetValueException** -of **SetValueInvocationException** -uitzonde ring.</span><span class="sxs-lookup"><span data-stu-id="663d0-112">All errors that occur when setting the value of an ETS property cause a **SetValueException** or **SetValueInvocationException** exception to be thrown.</span></span> <span data-ttu-id="663d0-113">Wanneer ETS detecteert dat er een fout is opgetreden, wordt een **SetValueException** -uitzonde ring gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-113">When ETS recognizes that an error occurred a **SetValueException** exception is thrown.</span></span> <span data-ttu-id="663d0-114">Wanneer de onderliggende setter van een eigenschap waarnaar wordt verwezen, detecteert dat er een fout is opgetreden, wordt er een **SetValueInvocationException** -uitzonde ring gegenereerd die de interne uitzonde ring kan bevatten die de ingestelde aanroep fout heeft veroorzaakt.</span><span class="sxs-lookup"><span data-stu-id="663d0-114">When the underlying setter of a referenced property recognizes that an error occurred, a **SetValueInvocationException** exception is thrown that may or may not include the inner exception that caused the set invocation error.</span></span>

## <a name="errors-invoking-a-method"></a><span data-ttu-id="663d0-115">Fouten bij het aanroepen van een methode</span><span class="sxs-lookup"><span data-stu-id="663d0-115">Errors invoking a method</span></span>

<span data-ttu-id="663d0-116">Alle fouten die optreden bij het aanroepen van een ETS-methode veroorzaken een **MethodException** -of **MethodInvocationException** -uitzonde ring.</span><span class="sxs-lookup"><span data-stu-id="663d0-116">All errors that occur when invoking an ETS method cause a **MethodException** or **MethodInvocationException** exception to be thrown.</span></span> <span data-ttu-id="663d0-117">Wanneer ETS detecteert dat er een fout is opgetreden, wordt een **MethodException** -uitzonde ring gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-117">When ETS recognizes that an error occurred a **MethodException** exception is thrown.</span></span> <span data-ttu-id="663d0-118">Wanneer de methode waarnaar wordt verwezen, detecteert dat er een fout is opgetreden, wordt er een **MethodInvocationException** -uitzonde ring gegenereerd die de binnenste uitzonde ring kan bevatten die de aanroep fout heeft veroorzaakt.</span><span class="sxs-lookup"><span data-stu-id="663d0-118">When the referenced method recognizes that an error occurred, a **MethodInvocationException** exception is thrown that may or may not include the inner exception that caused the invocation error.</span></span>

## <a name="casting-errors"></a><span data-ttu-id="663d0-119">Fouten casten</span><span class="sxs-lookup"><span data-stu-id="663d0-119">Casting errors</span></span>

<span data-ttu-id="663d0-120">Wanneer een ongeldige cast wordt geprobeerd, wordt een **PSInvalidCastException** gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-120">When an invalid cast is attempted, an **PSInvalidCastException** is thrown.</span></span> <span data-ttu-id="663d0-121">Omdat deze uitzonde ring is afgeleid van **System. InvalidCastException**, kan deze niet rechtstreeks worden onderschept vanuit het script.</span><span class="sxs-lookup"><span data-stu-id="663d0-121">Because this exception derives from **System.InvalidCastException**, it is not able to be directly trapped from script.</span></span> <span data-ttu-id="663d0-122">Houd er rekening mee dat de entiteit die de cast probeert, **PSInvalidCastException** in een **PSRuntimeException** moet teruglopen zodat deze kan worden onderschept door scripts.</span><span class="sxs-lookup"><span data-stu-id="663d0-122">Be aware that the entity attempting the cast would need to wrap **PSInvalidCastException** in an **PSRuntimeException** for this to be trappable by scripts.</span></span> <span data-ttu-id="663d0-123">Als er een poging wordt gedaan om de waarde van een **PSPropertySet**, **PSMemberSet**, **PSMethodInfo**of een lid van de **ReadOnlyPSMemberInfoCollection ' 1 '** in te stellen, wordt een **NotSupportedException** gegenereerd.</span><span class="sxs-lookup"><span data-stu-id="663d0-123">If an attempt is made to set the value of an **PSPropertySet**, **PSMemberSet**, **PSMethodInfo**, or a member of the **ReadOnlyPSMemberInfoCollection\`1**, a **NotSupportedException** is thrown.</span></span>

## <a name="common-runtime-errors"></a><span data-ttu-id="663d0-124">Veelvoorkomende runtime-fouten</span><span class="sxs-lookup"><span data-stu-id="663d0-124">Common runtime errors</span></span>

<span data-ttu-id="663d0-125">Alle andere veelvoorkomende runtime-fouten die optreden, zijn van het type **ExtendedTypeSystemException** Exception zonder extra specifieke uitzonderings typen.</span><span class="sxs-lookup"><span data-stu-id="663d0-125">Any other common runtime errors that occur are of type **ExtendedTypeSystemException** exception with no additional specific exception types.</span></span>

## <a name="initialization-errors"></a><span data-ttu-id="663d0-126">Initialisatie fouten</span><span class="sxs-lookup"><span data-stu-id="663d0-126">Initialization errors</span></span>

<span data-ttu-id="663d0-127">Er kunnen fouten optreden bij het initialiseren `types.ps1xml` .</span><span class="sxs-lookup"><span data-stu-id="663d0-127">Errors may occur when initializing `types.ps1xml`.</span></span> <span data-ttu-id="663d0-128">Deze fouten worden meestal weer gegeven wanneer de Power shell-runtime wordt gestart.</span><span class="sxs-lookup"><span data-stu-id="663d0-128">Typically, these errors are displayed when the PowerShell runtime starts.</span></span> <span data-ttu-id="663d0-129">Ze kunnen echter ook worden weer gegeven wanneer een module wordt geladen.</span><span class="sxs-lookup"><span data-stu-id="663d0-129">However, they can also be displayed when a module is loaded.</span></span>
